def generate_queries():
    return [ 
        {
            "name":"readOneLocal_book", 
            "query":"""{
                readOneLocal_book(book_id:"local_bk_12323"){
                    book_id
                    name
                    country_ids
                    publisher_id
                }
            }"""
        },
        { 
            "name":"readOneLocal_country", 
            "query":"""{
                readOneLocal_country(country_id:"local_ct_123232"){
                    country_id
                    name
                    book_ids
                }
            }"""
        },
        { 
            "name":"readOneLocal_capital", 
            "query":"""{
                readOneLocal_capital(capital_id:"local_cp_12322"){
                    capital_id
                    country_id
                    name
                }
            }"""
        },
        {
            "name":"readOneLocal_publisher", 
            "query":"""{
                readOnePublisher(publisher_id:"local_pb_190322"){
                    publisher_id
                    name
                }
            }"""
        },
        {
            "name":"readOneLocal_book_connection", 
            "query":"""{
                readOneLocal_book(book_id:"local_bk_12323"){
                    book_id
                    name
                    country_ids
                    publisher_id
                    local_countriesConnection(pagination: {first: 100}) {
                        local_countries {
                            name
                            country_id
                        }
                    }
                }
            }"""
        },
        { 
            "name":"readOneLocal_country_connection", 
            "query":"""{
                readOneLocal_country(country_id:"local_ct_123232"){
                    country_id
                    name
                    book_ids
                    available_local_booksConnection(pagination: {first: 100}) {
                        local_books {
                            book_id
                            name
                        }
                    }
                }
            }"""
        },
        { 
            "name":"readOneLocal_capital_connection", 
            "query":"""{
                readOneLocal_capital(capital_id:"local_cp_12322"){
                    capital_id
                    country_id
                    name
                    local_country{
                        country_id
                        name
                    }
                }
            }"""
        },
        {
            "name":"readOneLocal_publisher_connection", 
            "query":"""{
                readOneLocal_publisher(publisher_id:"local_pb_190322"){
                    publisher_id
                    name
                    booksConnection(pagination:{first: 100}){
                        local_books{
                            book_id
                            name
                        }
                    }
                }
            }"""
        },
        {
            "name":"readOneLocal_book_count", 
            "query":"""{
                readOneLocal_book(book_id:"local_bk_12323"){
                    book_id
                    name
                    country_ids
                    publisher_id
                    countFilteredLocal_countries(search: null)
                }
            }"""
        },
        { 
            "name":"readOneLocal_country_count", 
            "query":"""{
                readOneLocal_country(country_id:"local_ct_123232"){
                    country_id
                    name
                    book_ids
                    countFilteredAvailable_local_books(search: null)
                }
            }"""
        },
        {
            "name":"readOneLocal_publisher_count", 
            "query":"""{
                readOneLocal_publisher(publisher_id:"local_pb_190322"){
                    publisher_id
                    name
                    countFilteredBooks(search: null)
                }
            }"""
        },
        {
            "name":"countLocal_books", 
            "query":"""{
                countLocal_books(search:{field:book_id operator:like value:"local_bk%"})
            }"""
        },
        {
            "name":"countLocal_countries", 
            "query":"""query {
                countLocal_countries(search:{field:country_id operator:like value:"local_ct%"})
            }"""
        },
        {
            "name":"countLocal_capitals", 
            "query":"""{
                countLocal_capitals(search:{field:capital_id operator:like value:"local_cp%"})
            }"""
        },
        {
            "name":"countLocal_publishers", 
            "query":"""{
                countLocal_publishers(search:{field:publisher_id operator:like value:"local_pb%"})
            }"""
        },
        ]