def generate_queries(instance):
    return [ 
        {
            "name":"readOneBook_{instance}".format(instance=instance), 
            "query":"""{{
                readOneBook(book_id:"{instance}_bk_12323"){{
                    book_id
                    name
                    country_ids
                    publisher_id
                }}
            }}""".format(instance=instance)
        },
        { 
            "name":"readOneCountry_{instance}".format(instance=instance), 
            "query":"""{{
                readOneCountry(country_id:"{instance}_ct_123232"){{
                    country_id
                    name
                    book_ids
                }}
            }}""".format(instance=instance)
        },
        { 
            "name":"readOneCapital_{instance}".format(instance=instance), 
            "query":"""{{
                readOneCapital(capital_id:"{instance}_cp_12322"){{
                    capital_id
                    country_id
                    name
                }}
            }}""".format(instance=instance)
        },
        {
            "name":"readOnePublisher_{instance}".format(instance=instance), 
            "query":"""{{
                readOnePublisher(publisher_id:"{instance}_pb_190322"){{
                    publisher_id
                    name
                }}
            }}""".format(instance=instance)
        },
        {
            "name":"readOneBook_connection_{instance}".format(instance=instance), 
            "query":"""{{
                readOneBook(book_id:"{instance}_bk_12323"){{
                book_id
                name
                country_ids
                publisher_id
                countriesConnection(pagination: {{first:100}}){{
                    countries{{
                        country_id
                        name
                    }}
                }}
            }}""".format(instance=instance)
        },
        { 
            "name":"readOneCountry_connection_{instance}".format(instance=instance), 
            "query":"""{{
                readOneCountry(country_id:"{instance}_ct_123232"){{
                country_id
                name
                book_ids
                available_booksConnection(pagination: {{first:100}}){{
                    books{{
                        book_id
                        name
                    }}
                }}
            }}""".format(instance=instance)
        },
        { 
            "name":"readOneCapital_connection_{instance}".format(instance=instance), 
            "query":"""{{
                readOneCapital(capital_id:"{instance}_cp_12322"){{
                    capital_id
                    country_id
                    name
                    country(search: null){{
                        country_id
                        name
                    }}
                }}
            }}""".format(instance=instance)
        },
        {
            "name":"readOnePublisher_connection_{instance}".format(instance=instance), 
            "query":"""{{
                readOnePublisher(publisher_id:"{instance}_pb_190322"){{
                    publisher_id
                    name
                    booksConnection(pagination: {{first:100}}){{
                        books{{
                            book_id
                            name
                        }}
                    }}
                    countFilteredBooks(search: null)
                }}
            }}""".format(instance=instance)
        },
        {
            "name":"readOneBook_count_{instance}".format(instance=instance), 
            "query":"""{{
                readOneBook(book_id:"{instance}_bk_12323"){{
                book_id
                name
                country_ids
                publisher_id
                countFilteredCountries(search: null)
                }}
            }}""".format(instance=instance)
        },
        { 
            "name":"readOneCountry_count_{instance}".format(instance=instance), 
            "query":"""{{
                readOneCountry(country_id:"{instance}_ct_123232"){{
                country_id
                name
                book_ids
                countFilteredAvailable_books(search: null)
                }}
            }}""".format(instance=instance)
        },

        {
            "name":"readOnePublisher_count_{instance}".format(instance=instance), 
            "query":"""{{
                readOnePublisher(publisher_id:"{instance}_pb_190322"){{
                    publisher_id
                    name
                    countFilteredBooks(search: null)
                }}
            }}""".format(instance=instance)
        },
        ]